server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/buchstadt?allowMultiQueries=true
  global-prefix: api

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.buchstadt.pojo
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true